name: Build Citadel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install System Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools libxcb-shm0-dev libxcb-xfixes0-dev

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build App (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Build App (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Build App (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
